/**
 * Rocket — content tables.
 *
 * Every sprite name here must exist in `frontend/public/rocket/manifest.json`
 * (generated by `scripts/rocket/extract-sprites.js`). `assets.ts` validates the
 * list at boot and fails loudly on a typo, so a bad name is a startup error
 * rather than an invisible green box at a tense moment.
 */

import { SHIPS } from './ships';
import type { EffectKind, EnemyDef, EnemyKind, PickupDef, PickupKind } from './types';
import { UPGRADES } from './upgrades';

export const ENEMY_DEFS: Record<EnemyKind, EnemyDef> = {
  /** Tiny fast shrapnel. Introduced in wave 1 so the player can learn to move. */
  debris: {
    kind: 'debris',
    hp: 6,
    radius: 18,
    speed: 0.34,
    score: 10,
    coins: 1,
    fireMs: 0,
    shotDamage: 0,
    sprites: [
      'debris-shard',
      'debris-shards',
      'debris-shards-2',
      'debris-chips',
      'debris-fragments',
      'debris-nuts',
      'debris-bolts',
    ],
    artPointsUp: false,
    deathEffect: 'spark',
  },
  /** Slow, chunky, worth hitting. The bread-and-butter target. */
  asteroid: {
    kind: 'asteroid',
    hp: 24,
    radius: 34,
    speed: 0.18,
    score: 25,
    coins: 2,
    fireMs: 0,
    shotDamage: 0,
    sprites: [
      'asteroid-orange',
      'asteroid-blue',
      'asteroid-teal',
      'asteroid-green',
      'asteroid-orange-2',
      'asteroid-blue-2',
      'asteroid-green-2',
      'moon-grey',
      'moon-tan',
      'moon-brown',
    ],
    artPointsUp: false,
    deathEffect: 'explosion-small',
  },
  /** Drifts, then lobs a slow orb. Punishes standing still. */
  mine: {
    kind: 'mine',
    hp: 18,
    radius: 26,
    speed: 0.14,
    score: 30,
    coins: 2,
    fireMs: 2200,
    shotDamage: 1,
    sprites: [
      'mine-spike-red',
      'mine-spike-red-2',
      'mine-dome-red',
      'mine-core-orange',
      'mine-alert-grey',
    ],
    artPointsUp: false,
    deathEffect: 'explosion-small',
  },
  /** Strafes across the screen and fires aimed shots. */
  drone: {
    kind: 'drone',
    hp: 34,
    radius: 30,
    speed: 0.22,
    score: 45,
    coins: 3,
    fireMs: 1550,
    shotDamage: 1,
    sprites: [
      'satellite-sputnik',
      'satellite-sputnik-2',
      'satellite-grey',
      'satellite-grey-2',
      'satellite-panels',
      'satellite-panels-2',
      'satellite-dish',
      'satellite-dish-2',
    ],
    artPointsUp: false,
    deathEffect: 'explosion',
  },
  /** Heavy hull, fires a spread. Worth dodging rather than trading with. */
  gunship: {
    kind: 'gunship',
    hp: 95,
    radius: 46,
    speed: 0.13,
    score: 120,
    coins: 6,
    fireMs: 1950,
    shotDamage: 1,
    sprites: ['lifter-rocket-2', 'lifter-rocket-3', 'lifter-rocket-4', 'lifter-rocket-5'],
    // The only vehicle art: a rocket with its nose at the top of the sprite.
    artPointsUp: true,
    deathEffect: 'explosion',
  },
  /** Wave boss: a screen-filling spiky sun. */
  boss: {
    kind: 'boss',
    hp: 620,
    radius: 104,
    speed: 0.075,
    score: 900,
    coins: 40,
    fireMs: 1250,
    shotDamage: 2,
    sprites: ['sun-spiky-gold', 'sun-spiky-orange', 'sun-spiky-red', 'sun-spiky-teal'],
    artPointsUp: false,
    deathEffect: 'explosion',
  },
};

export const PICKUP_DEFS: Record<PickupKind, PickupDef> = {
  coin: {
    kind: 'coin',
    value: 1,
    radius: 16,
    sprites: ['currency-coins', 'coins-stack', 'coin-gold', 'medal-star-gold'],
  },
  gem: {
    kind: 'gem',
    value: 5,
    radius: 18,
    sprites: [
      'gem-diamond-green',
      'gem-brilliant-green',
      'gems-collection',
      'crystals',
      'crystal-cluster-pink',
      'gem-diamond-emerald',
    ],
  },
  shield: {
    kind: 'shield',
    value: 1,
    radius: 20,
    sprites: ['shield-bubble-blue', 'orb-shield-blue'],
  },
  repair: {
    kind: 'repair',
    value: 1,
    radius: 20,
    sprites: ['fuel-can-grey', 'fuel-can-red', 'oxygen-tank', 'fuel-can-orange'],
  },
};

/**
 * Ordered animation frames per effect kind. Order is the playback order, so
 * these lists are intentionally hand-picked rather than "all the sprites that
 * matched a prefix".
 */
export const EFFECT_FRAMES: Record<EffectKind, string[]> = {
  explosion: [
    'explosion-small-red',
    'explosion-red',
    'explosion-red-2',
    'explosion-blast',
    'explosion-blast-2',
    'smoke-trail',
    'smoke-wisp',
  ],
  'explosion-small': ['spark-burst', 'explosion-small-red-2', 'explosion-small-red-3', 'smoke-wisp'],
  'shield-hit': [
    'shield-hit-blue-burst',
    'spark-burst-6',
    'spark-burst-7',
  ],
  spark: ['spark-burst-3', 'spark-burst-4', 'spark-burst-5'],
  smoke: ['smoke-trail', 'smoke-wisp'],
};

/** Player bullets by weapon tier: single → twin → triple. */
export const PLAYER_BULLETS: string[] = ['plasma-ball-blue', 'plasma-ball-arcs'];

/** Enemy bullets, picked per shot so incoming fire reads as a different thing. */
export const ENEMY_BULLETS: string[] = [
  'power-bolt-yellow',
  'power-bolt-yellow-2',
  'orb-water',
  'orb-green',
  'power-bolt-blue',
];

/** Thruster flames drawn under the player's ship (keyed by ship). */
export const THRUSTER: Record<string, string> = {
  scout: 'exhaust-trail-blue',
  hauler: 'flame-small',
  retro: 'flame-thin',
};

/** Backgrounds offered on the menu; the play scene drifts them slowly. */
export const BACKGROUNDS: string[] = [
  'bg-nebula-blue',
  'bg-nebula-purple',
  'bg-nebula-pink',
  'bg-galaxy',
];

/** Sprite used for the star/debris parallax layer in the background. */
export const STAR_SPRITES: string[] = [
  'star-sparkle-blue',
  'star-sparkle-gold',
  'debris-chips',
  'debris-shard',
];

/**
 * Every sprite name the game can ask for. `assets.ts` loads exactly these —
 * nothing else in the 282-sprite set needs to reach the browser.
 */
export function requiredSprites(): string[] {
  const names = new Set<string>();
  for (const def of Object.values(ENEMY_DEFS)) def.sprites.forEach((s) => names.add(s));
  for (const def of Object.values(PICKUP_DEFS)) def.sprites.forEach((s) => names.add(s));
  for (const frames of Object.values(EFFECT_FRAMES)) frames.forEach((s) => names.add(s));
  PLAYER_BULLETS.forEach((s) => names.add(s));
  ENEMY_BULLETS.forEach((s) => names.add(s));
  Object.values(THRUSTER).forEach((s) => names.add(s));
  BACKGROUNDS.forEach((s) => names.add(s));
  STAR_SPRITES.forEach((s) => names.add(s));
  // Playable ships are chosen from the menu rather than spawned, so they are
  // easy to forget here — and a ship that was never loaded shows up as an
  // opaque green box on the very first screen.
  Object.values(SHIPS).forEach((def) => names.add(def.sprite));
  // Shop icons are the same trap: only ever drawn on the between-wave screen.
  Object.values(UPGRADES).forEach((def) => names.add(def.sprite));
  return [...names].sort();
}
