// Question bank for the IQ Test page.
// categories: english | reading | science | logic
// diff (difficulty): 1 = easy, 2 = medium, 3 = hard — used to weight scoring.
const BANK = [
  // ---------------- ENGLISH ----------------
  { cat: 'english', diff: 1, q: "Which word is a synonym for 'happy'?", options: ['Joyful', 'Angry', 'Tired', 'Confused'], answer: 0, exp: "'Joyful' means feeling or showing great happiness." },
  { cat: 'english', diff: 1, q: 'Choose the correctly spelled word.', options: ['Recieve', 'Receive', 'Receeve', 'Receve'], answer: 1, exp: "The rule is 'i before e except after c' — but this is an exception where 'ei' follows 'c': R-E-C-E-I-V-E." },
  { cat: 'english', diff: 2, q: "Which sentence uses the correct form of 'their/there/they're'?", options: ['Their going to the store.', "They're going to the store.", 'There going to the store.', 'Theyre going to the store.'], answer: 1, exp: "'They're' is the contraction of 'they are', which fits this sentence." },
  { cat: 'english', diff: 2, q: "What is the antonym of 'benevolent'?", options: ['Kind', 'Generous', 'Malevolent', 'Charitable'], answer: 2, exp: "'Malevolent' means having ill will, the opposite of 'benevolent' (kind, generous)." },
  { cat: 'english', diff: 2, q: 'Identify the verb in this sentence: "The quick fox jumps over the lazy dog."', options: ['Quick', 'Jumps', 'Lazy', 'Dog'], answer: 1, exp: "'Jumps' is the action word (verb) in the sentence." },
  { cat: 'english', diff: 2, q: "Which word means 'a large group of stars'?", options: ['Galaxy', 'Meteor', 'Comet', 'Nebula'], answer: 0, exp: "A 'galaxy' is a massive collection of stars, gas, and dust bound by gravity." },
  { cat: 'english', diff: 3, q: 'Which sentence contains a dangling modifier?', options: ['Running quickly, the finish line came into view.', 'She ran quickly to the finish line.', 'Running quickly, she reached the finish line.', 'The finish line was near, so she ran quickly.'], answer: 0, exp: "In the first sentence, 'Running quickly' has no clear subject to modify — the finish line isn't running." },
  { cat: 'english', diff: 1, q: "What is the plural of 'child'?", options: ['Childs', 'Childes', 'Children', 'Childrens'], answer: 2, exp: "'Children' is the irregular plural form of 'child'." },
  { cat: 'english', diff: 2, q: 'Which word is an adverb?', options: ['Quickly', 'Quick', 'Quickness', 'Quicken'], answer: 0, exp: "'Quickly' modifies a verb and ends in '-ly', a common adverb pattern." },
  { cat: 'english', diff: 3, q: 'Choose the sentence written in passive voice.', options: ['The chef cooked the meal.', 'The meal was cooked by the chef.', 'The chef is cooking the meal.', 'The chef will cook the meal.'], answer: 1, exp: "Passive voice puts the object first: 'The meal was cooked by the chef' — the subject receives the action." },
  { cat: 'english', diff: 2, q: "What does the idiom 'to bite the bullet' mean?", options: ['To eat quickly', 'To face a difficult situation with courage', 'To argue with someone', 'To avoid a task'], answer: 1, exp: "'Bite the bullet' means to endure a painful or unpleasant situation bravely." },
  { cat: 'english', diff: 1, q: 'Which of these is a proper noun?', options: ['city', 'river', 'Paris', 'building'], answer: 2, exp: "'Paris' names a specific place, making it a proper noun (capitalized)." },
  { cat: 'english', diff: 3, q: "Which word best completes: 'Her explanation was so ___ that no one had further questions.'", options: ['ambiguous', 'lucid', 'vague', 'cryptic'], answer: 1, exp: "'Lucid' means clear and easy to understand, matching 'no one had further questions'." },
  { cat: 'english', diff: 2, q: "Which punctuation correctly joins these clauses? 'I wanted to go for a walk ___ it started raining.'", options: ['but', 'and', 'so', 'or'], answer: 0, exp: "'But' shows contrast between wanting to walk and the rain stopping that plan." },
  { cat: 'english', diff: 3, q: "Which figure of speech is used in 'The classroom was a zoo'?", options: ['Simile', 'Metaphor', 'Personification', 'Hyperbole'], answer: 1, exp: 'A metaphor directly states one thing IS another without using "like" or "as".' },

  // ---------------- READING COMPREHENSION ----------------
  { cat: 'reading', diff: 1, passage: 'Bees play a critical role in pollinating flowers and crops. Without bees, many plants would struggle to reproduce, which would affect the food supply for humans and animals alike.', q: 'According to the passage, why are bees important?', options: ['They produce honey for humans only', 'They pollinate flowers and crops', 'They protect crops from pests', 'They provide wax for candles'], answer: 1, exp: 'The passage states bees are critical for pollinating flowers and crops.' },
  { cat: 'reading', diff: 2, passage: 'Despite the storm warnings, Maria decided to go sailing. She believed her experience would keep her safe, but two hours later the coast guard had to rescue her from rough waters.', q: "What can be inferred about Maria's decision?", options: ['It was a wise choice', 'It turned out to be risky', 'She had no sailing experience', 'The coast guard ignored her'], answer: 1, exp: 'She needed rescuing despite her confidence, implying the decision was risky.' },
  { cat: 'reading', diff: 1, passage: "The library will be closed on Monday for renovations. It will reopen Tuesday at 9 a.m. with a new children's reading section.", q: 'When will the library reopen?', options: ['Monday', 'Tuesday at 9 a.m.', 'Wednesday', 'It will not reopen'], answer: 1, exp: 'The passage directly states it reopens Tuesday at 9 a.m.' },
  { cat: 'reading', diff: 2, passage: 'Although Sam had studied all week, he felt nervous walking into the exam room. He reminded himself that preparation reduces, but never fully eliminates, anxiety.', q: 'What is the main idea of this passage?', options: ['Studying guarantees no nervousness', 'Preparation can lessen but not remove anxiety', 'Sam did not study enough', 'Exams should be avoided'], answer: 1, exp: "The passage's key point is that preparation reduces anxiety but doesn't eliminate it entirely." },
  { cat: 'reading', diff: 3, passage: 'The committee debated for hours, yet no consensus emerged. Some argued that swift action was necessary, while others cautioned that haste could lead to costly mistakes. In the end, they agreed to revisit the issue after gathering more data.', q: "What was the outcome of the committee's debate?", options: ['They took swift action immediately', 'They abandoned the issue entirely', 'They postponed the decision pending more information', 'They split into two permanent factions'], answer: 2, exp: 'The passage says they agreed to revisit the issue after gathering more data — a postponement.' },
  { cat: 'reading', diff: 2, passage: 'Recycling helps conserve natural resources and reduces landfill waste. However, contamination — such as mixing food waste with recyclables — can cause entire batches to be rejected at processing facilities.', q: 'What can cause a batch of recyclables to be rejected?', options: ['Too much plastic', 'Contamination from food waste', 'Using too many bins', 'Recycling on the wrong day'], answer: 1, exp: 'The passage explains contamination, like food waste mixed in, causes rejection.' },
  { cat: 'reading', diff: 1, passage: 'After the rain stopped, a bright rainbow appeared over the hills. Children ran outside to see it before it faded away.', q: 'What happened right before the rainbow appeared?', options: ['The sun set', 'The rain stopped', 'The children went inside', 'It began to snow'], answer: 1, exp: 'The passage states the rainbow appeared after the rain stopped.' },
  { cat: 'reading', diff: 3, passage: 'Historians often disagree not because the facts are unclear, but because they weigh those facts differently based on their own perspectives and the questions they consider important.', q: 'According to the passage, why do historians often disagree?', options: ['The facts are usually missing', 'They weigh facts differently based on perspective', 'They refuse to read primary sources', 'There is only one correct interpretation'], answer: 1, exp: 'The passage explicitly says disagreement comes from weighing facts differently, not from unclear facts.' },
  { cat: 'reading', diff: 2, passage: 'The new policy requires all employees to complete safety training within 30 days of hire. Failure to comply may result in restricted access to certain work areas.', q: "What happens if an employee doesn't complete training in time?", options: ['They are fired immediately', 'Nothing happens', 'They may have restricted access to work areas', 'They get a pay raise'], answer: 2, exp: 'The passage states non-compliance may result in restricted access to certain areas.' },
  { cat: 'reading', diff: 1, passage: 'Elephants are the largest land animals on Earth. They use their trunks for breathing, drinking, and grabbing objects.', q: "What is one use of an elephant's trunk mentioned in the passage?", options: ['Flying', 'Grabbing objects', 'Digging tunnels', 'Building nests'], answer: 1, exp: 'The passage lists breathing, drinking, and grabbing objects as trunk uses.' },
  { cat: 'reading', diff: 2, passage: 'The startup grew quickly, but its rapid hiring outpaced its training programs, leaving many new employees confused about their responsibilities.', q: 'What problem did the startup face?', options: ['Too few customers', 'Hiring outpaced training, causing confusion', 'The company grew too slowly', 'Employees refused to be trained'], answer: 1, exp: 'The passage says hiring outpaced training programs, leading to confusion.' },
  { cat: 'reading', diff: 3, passage: "While critics praised the film's visual style, many felt its plot lacked depth, resulting in a work that was admired more for its craft than its storytelling.", q: 'What is the overall critical view of the film described?', options: ['It was praised entirely without criticism', 'It was visually impressive but weak in story', 'It had a strong story but poor visuals', 'It received no attention at all'], answer: 1, exp: 'The passage contrasts praised visuals with a plot that lacked depth.' },
  { cat: 'reading', diff: 1, passage: "Marcus packed his bag the night before his trip so he wouldn't have to rush in the morning.", q: 'Why did Marcus pack the night before?', options: ['He forgot his bag', "So he wouldn't have to rush in the morning", 'Because it was raining', 'He had extra bags to pack'], answer: 1, exp: 'The passage directly gives this reason.' },
  { cat: 'reading', diff: 2, passage: 'The report recommended increased funding for public transit, citing reduced traffic congestion and lower emissions as key benefits, though it acknowledged the high upfront costs.', q: 'What downside does the report acknowledge?', options: ['Increased traffic', 'Higher emissions', 'High upfront costs', 'Reduced ridership'], answer: 2, exp: 'The passage explicitly names high upfront costs as an acknowledged downside.' },
  { cat: 'reading', diff: 3, passage: "The scientist's hypothesis was not disproven by the experiment; rather, the results were inconclusive, prompting calls for a larger, more controlled follow-up study.", q: 'What was the result of the experiment?', options: ['The hypothesis was proven true', 'The hypothesis was disproven', 'The results were inconclusive', 'The experiment was cancelled'], answer: 2, exp: 'The passage states the results were inconclusive, not proven or disproven.' },

  // ---------------- SCIENCE ----------------
  { cat: 'science', diff: 1, q: 'What gas do plants primarily absorb from the atmosphere for photosynthesis?', options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], answer: 2, exp: 'Plants absorb carbon dioxide (CO2) and use sunlight to convert it into glucose and oxygen.' },
  { cat: 'science', diff: 1, q: 'What is the chemical symbol for water?', options: ['H2O', 'CO2', 'O2', 'NaCl'], answer: 0, exp: 'Water is composed of two hydrogen atoms and one oxygen atom: H2O.' },
  { cat: 'science', diff: 2, q: "Which planet is known as the 'Red Planet'?", options: ['Venus', 'Mars', 'Jupiter', 'Saturn'], answer: 1, exp: 'Mars appears red due to iron oxide (rust) on its surface.' },
  { cat: 'science', diff: 2, q: 'What force keeps planets in orbit around the sun?', options: ['Magnetism', 'Gravity', 'Friction', 'Nuclear force'], answer: 1, exp: 'Gravity is the attractive force between masses that keeps planets orbiting the sun.' },
  { cat: 'science', diff: 2, q: 'Which organ in the human body is primarily responsible for pumping blood?', options: ['Lungs', 'Liver', 'Heart', 'Kidneys'], answer: 2, exp: 'The heart pumps blood through the circulatory system.' },
  { cat: 'science', diff: 3, q: 'What is the process by which cells divide to produce two identical daughter cells called?', options: ['Meiosis', 'Mitosis', 'Osmosis', 'Photosynthesis'], answer: 1, exp: 'Mitosis is cell division producing two genetically identical daughter cells.' },
  { cat: 'science', diff: 1, q: 'What is the boiling point of water at sea level in Celsius?', options: ['0°C', '50°C', '100°C', '212°C'], answer: 2, exp: 'Water boils at 100°C (212°F) at standard atmospheric pressure.' },
  { cat: 'science', diff: 2, q: 'Which of these is a renewable energy source?', options: ['Coal', 'Natural gas', 'Solar power', 'Petroleum'], answer: 2, exp: 'Solar power is renewable because sunlight is continuously available, unlike fossil fuels.' },
  { cat: 'science', diff: 3, q: "What is Newton's Third Law of Motion?", options: ['An object in motion stays in motion', 'Force equals mass times acceleration', 'For every action there is an equal and opposite reaction', 'Energy cannot be created or destroyed'], answer: 2, exp: "Newton's Third Law states that every action has an equal and opposite reaction." },
  { cat: 'science', diff: 2, q: 'What part of the cell contains its genetic material?', options: ['Mitochondria', 'Nucleus', 'Ribosome', 'Cytoplasm'], answer: 1, exp: "The nucleus houses DNA, the cell's genetic material." },
  { cat: 'science', diff: 1, q: 'How many bones are in the adult human body (approximately)?', options: ['106', '206', '306', '406'], answer: 1, exp: 'The adult human skeleton has approximately 206 bones.' },
  { cat: 'science', diff: 3, q: 'What causes tides on Earth?', options: ['Wind patterns', 'The gravitational pull of the moon and sun', 'Ocean currents alone', "Earth's rotation only"], answer: 1, exp: 'Tides are primarily caused by the gravitational pull of the moon (and to a lesser extent the sun).' },
  { cat: 'science', diff: 2, q: 'Which state of matter has a fixed volume but no fixed shape?', options: ['Solid', 'Liquid', 'Gas', 'Plasma'], answer: 1, exp: 'Liquids take the shape of their container but maintain a fixed volume.' },
  { cat: 'science', diff: 3, q: 'What is the powerhouse of the cell, responsible for producing energy (ATP)?', options: ['Nucleus', 'Golgi apparatus', 'Mitochondria', 'Endoplasmic reticulum'], answer: 2, exp: "Mitochondria generate ATP, the cell's main energy currency, earning the nickname 'powerhouse of the cell'." },
  { cat: 'science', diff: 2, q: "Which element has the chemical symbol 'Fe'?", options: ['Fluorine', 'Iron', 'Francium', 'Lead'], answer: 1, exp: "'Fe' comes from the Latin 'ferrum', meaning iron." },

  // ---------------- LOGIC / MATCH / PATTERN ----------------
  { cat: 'logic', diff: 1, q: 'Complete the sequence: 2, 4, 6, 8, ___', options: ['9', '10', '12', '14'], answer: 1, exp: 'The sequence increases by 2 each time, so the next number is 10.' },
  { cat: 'logic', diff: 2, q: 'Complete the sequence: 3, 6, 12, 24, ___', options: ['30', '36', '48', '60'], answer: 2, exp: 'Each number doubles the previous one: 24 × 2 = 48.' },
  { cat: 'logic', diff: 2, q: 'Which word does NOT belong with the others?', options: ['Apple', 'Banana', 'Carrot', 'Grape'], answer: 2, exp: "Apple, banana, and grape are fruits; carrot is a vegetable — it doesn't match the group." },
  { cat: 'logic', diff: 1, q: 'Book is to Reading as Fork is to ___?', options: ['Cooking', 'Eating', 'Kitchen', 'Spoon'], answer: 1, exp: 'A book is used for reading, just as a fork is used for eating — matching tool-to-action pairs.' },
  { cat: 'logic', diff: 2, q: 'If all Zips are Zops, and all Zops are Zaps, then all Zips are ___?', options: ['Zops only', 'Zaps', 'Neither Zops nor Zaps', 'Cannot be determined'], answer: 1, exp: 'By transitive logic: Zips → Zops → Zaps, so all Zips are Zaps.' },
  { cat: 'logic', diff: 3, q: 'Complete the pattern: A, C, F, J, ___', options: ['M', 'N', 'O', 'P'], answer: 2, exp: 'The gaps increase by one each time (+2, +3, +4, +5): A(1)→C(3)→F(6)→J(10)→O(15).' },
  { cat: 'logic', diff: 1, q: 'Which shape comes next in this sequence: Circle, Square, Circle, Square, ___?', options: ['Circle', 'Square', 'Triangle', 'Star'], answer: 0, exp: 'The pattern alternates Circle, Square — so it repeats with Circle next.' },
  { cat: 'logic', diff: 2, q: 'Hand is to Glove as Foot is to ___?', options: ['Sock', 'Shoe', 'Toe', 'Leg'], answer: 1, exp: 'A glove covers a hand the way a shoe covers a foot — the classic covering-item analogy pairing.' },
  { cat: 'logic', diff: 3, q: 'Complete the number series: 1, 1, 2, 3, 5, 8, ___', options: ['11', '12', '13', '14'], answer: 2, exp: 'This is the Fibonacci sequence — each number is the sum of the two before it: 5 + 8 = 13.' },
  { cat: 'logic', diff: 2, q: 'Which number does not belong: 3, 5, 7, 10, 11', options: ['3', '5', '10', '11'], answer: 2, exp: '3, 5, 7, and 11 are all prime numbers; 10 is not prime.' },
  { cat: 'logic', diff: 1, q: 'If today is Monday, what day will it be in 3 days?', options: ['Tuesday', 'Wednesday', 'Thursday', 'Friday'], answer: 2, exp: 'Monday + 3 days = Thursday.' },
  { cat: 'logic', diff: 3, q: 'A clock shows 3:15. What is the angle between the hour and minute hands (approximately)?', options: ['0°', '7.5°', '37.5°', '90°'], answer: 2, exp: 'At 3:15, the hour hand has moved a quarter of the way from 3 to 4 (about 7.5°), and the minute hand is at the 3 (90° mark), giving an approximate 37.5° gap.' },
  { cat: 'logic', diff: 2, q: 'Complete the analogy: Bird is to Nest as Bee is to ___?', options: ['Flower', 'Hive', 'Sting', 'Honey'], answer: 1, exp: 'A bird lives in a nest, just as a bee lives in a hive — matching the animal-to-home relationship.' },
  { cat: 'logic', diff: 2, q: 'Which figure completes the pattern logically: Triangle(3 sides), Square(4 sides), Pentagon(5 sides), ___?', options: ['Hexagon(6 sides)', 'Circle(0 sides)', 'Line(1 side)', 'Point(0 sides)'], answer: 0, exp: 'The pattern increases sides by one each time, so a Hexagon with 6 sides comes next.' },
  { cat: 'logic', diff: 3, q: 'Complete the sequence: 100, 50, 25, 12.5, ___', options: ['6.25', '6', '5', '10'], answer: 0, exp: 'Each term is half the previous one: 12.5 ÷ 2 = 6.25.' }
];

export const CAT_LABELS = { english: 'English', reading: 'Reading', science: 'Science', logic: 'Logic' };
export const CAT_KEYS = ['english', 'reading', 'science', 'logic'];
export const PER_CATEGORY = 5;

export default BANK;
